theme: jekyll-theme-hacker
title: Customized ComfyUI Documentation
description: REST API, MCP Server, and AI Art Director for ComfyUI.
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
